language: node_js
env: NPS=pwsh
matrix:
  include:
      # linux 16.04 - pwsh
    - os: linux
      dist: xenial
      sudo: required
      node_js:
        - "lts/*"
        - "lts/boron"
      before_install:
        - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo apt-get update
        - sudo apt-get install -y powershell
      # osx - pwsh
    - os: osx
      node_js:
        - "lts/*"
        - "lts/boron"
      before_install: brew cask install powershell
      # windows - pwsh
    - os: windows
      env: 
        - NPS=pwsh
        - YARN_GPG=no
      node_js:
        - "lts/*"
        - "lts/boron"
      before_install:
        - sudo apt-get install unzip jq
        - wget -q -nv -O- https://api.github.com/repos/PowerShell/PowerShell/releases/latest 2>/dev/null |  jq -r '.assets[] | select(.browser_download_url | contains("win-x64.zip")) | .browser_download_url' | wget -i - -O /tmp/pwsh.zip
        - unzip /tmp/pwsh.zip -d ./pwsh
        - export PATH=$PATH:$PWD/casperjs-1.0.2/bin/
      # windows - powershell
    - os: windows
      env: 
        - NPS=powershell
        - YARN_GPG=no
      node_js:
        - "lts/*"
        - "lts/boron"
cache: npm
install:
  - npm install 
  # - npm install -g gulp
script:
  # - npm run build
  - npm run lint
  - npm run test
after_success: npm run coverage
deploy:
  provider: npm
  email: "rannn505@outlook.com"
  api_key: "UuLITFEY1xvsz7HYkImWQSYYh6a8Q/jNn9X2OMecT5IUGxLBzT7BK11O7Fi2ZQSH2vdCTNasP3XPqKu6ogPKP7UKQCqpVoPLzzUr/2jVpgSj4fUjb5K0Tw8V7Z4+3YAm4rT8nsK9GVZHthp677e3lkTuRWvIsLOxq1epV137fvVhswt9rC0hHC9S3PtRG7BmFtyo7hFmE2xGbJoPfkmHuAHU6shKJWio9MlNSunpJ1erbT0z8Vqu0ryVMN0sa6v9ZaLD1w6Zw+BRE7knNCk2e9hY0yhlkXLViy0vVrn6Ut+UYfjafLHKa4x8Ms9Q96ZzLarUf47GaEFlavWxnLjEWOST80HpQe6tvmtxLQlU2kKSzdyPiFysadfvnQPOL3D9lunSPp+KJGWvbuAPQKBBtJivaSGV9+BQjKn/ujZvaNNSty2kGgNQYugKqCHrs7M+l0nazyT34H6QakA2KhgfFVN3mAOZvAT4f/CLLOHhVl87seMSQTGp8J9vxUWnscHxggFnZtVu8cRzI6lMuu/VyqEYL5TtO3b9J7cuH+zy5a4FIFhrO2Kgxqk/OnxfHoD7IAr0WDuCQy9rvu6UVBhTV5ZbLacOxWPnktwcJAj6QZBPCjPFrlrRA2XuEXMAmsE+PzJAfxbKsT+82qiXIBgaXEd8BwtuUtHHu4A29nT0QK4="
  on:
    branch: master
    tags: true
